vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        logo_file:
            uri_prefix: /uploads/logos
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
