vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        profilepicture_file:
            uri_prefix: /uploads/profilepictures
            upload_destination: '%upload_directory_profilepictures%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        thumbnail_file:
            uri_prefix: /uploads/thumbnails
            upload_destination: "%upload_directory_thumbnails%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        video_file:
            uri_prefix: /uploads/videos
            upload_destination: "%upload_directory_videos%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
