vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        miniature_file:
            uri_prefix: /uploads/images/miniatures
            upload_destination: "%upload_directory%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        video_file:
            uri_prefix: /uploads/videos
            upload_destination: "%upload_directory%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
