vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        poster_file:
            uri_prefix: /uploads/logos
            upload_destination: '%upload_directory_logos%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
